import React from "react"
import { List } from "semantic-ui-react";


const ArticleItem = (props) => {
    const { article } = props;
    return <List.Item>{article.title}</List.Item>
};

const ArticleList = (props) => {
    return (
        <List divided style={{ maxWidth: 900, margin: "0 auto" }}>
            {props.articles.map((article) => (
                <ArticleItem article={article} key={article.title + index} />
            ))}
        </List>
    );
};
// key could be generated by shortid, need one if list needs to dynamically change 
// passed down an array of articles as a prop
// the array of articles can be accessed with props.articles within the component

// <List.Item key={article, title + index}>{article.title}</List.Item>